---
title: "Isotope_workspace"
output: html_document
---

```{r}
install.packages('rnoaa')
```

```{r}
install.packages('zoo')
```

```{r}
install.packages("deseasonalize")
```

```{r}
install.packages('forecast')
```


```{r}
library(rnoaa)
library(zoo)
library(deseasonalize)
library(forecast)
library(ggplot2)
```

noaaGet

```{r}
noaaGet <- function(station, dtype, beginyr, endyr){
  Values <- vector(mode="list",length=1)
  for (year in seq(beginyr, endyr)){
  stDate <- paste0(year, "-01-01")
  endDate <- paste0(year, "-12-31")
 Tdat <- ncdc(datasetid='GSOM', stationid = station, datatypeid=dtype, startdate = stDate, enddate = endDate, limit = 100, add_units=TRUE)
 name <- paste0(dtype, year)
  Values[[name]] <- Tdat[[2]]
  }
  totyr <- (endyr - beginyr + 2)
Combined <- rbind(Values[[2]], Values[[3]])
  for (num in 4:totyr){
    Combined <- rbind(Combined, Values[[num]])
  }
return(Combined)
}
```

read in isotope data

```{r}
data.path <- "./IsotopeData/"
glob.path <- paste0(data.path, "*", ".csv")  
dataFiles <- Sys.glob(glob.path)
for(x in 1:5){
  temporaryFile <- read.csv(dataFiles[x])
  assign(basename(dataFiles[x]), temporaryFile)
}
```

Tool to combine temp, precip, and O18 time series

```{r}
isoTempCompare <- function(iso, temp, precip){
  temp$date <- strtrim(temp$date, 10)
  precip$date <- strtrim(precip$date, 10)
  zooIso <- zoo(iso[,c(17)], as.Date(iso[, 14]))
  zooTemp <- zoo(temp[,4], as.Date(temp$date))
  zooPrecip <- zoo(precip[,4], as.Date(precip$date))
  IsoTimeSeries <- merge(zooTemp, zooPrecip, zooIso, all=FALSE)
  colnames(IsoTimeSeries) <- c("Temp","Precip","O18")
  return(IsoTimeSeries)
}
```

```{r}
iso2 <- isoTempCompare(CG_iso, grim_temp, grim_precip)
iso2
```

```{r}
plot(iso2, plot.type = 'multiple', col = c('red', 'blue', 'green'), lwd=2)
```

read in and plot O18 for multiple sites (IN PROGRESS)

```{r}
IsoCompare <- function(first, second, third=NULL, fourth=NULL, fifth=NULL){
  zooIso1 <- zoo(first[,c(17)], as.Date(first[, 14]))
  zooIso2 <- zoo(second[,c(17)], as.Date(second[, 14]))
  IsoCombined <- merge(zooIso1, zooIso2)
  if(!is.null(third)){
    zooIso3 <- zoo(third[,c(17)], as.Date(third[, 14]))
    IsoCombined <- merge(IsoCombined, zooIso3)
  }
  if(!is.null(fourth)){
    zooIso4 <- zoo(fourth[,c(17)], as.Date(fourth[, 14]))
    IsoCombined <- merge(IsoCombined, zooIso4)
  }
  if(!is.null(fifth)){
    zooIso5 <- zoo(fifth[,c(17)], as.Date(fifth[, 14]))
    IsoCombined <- merge(IsoCombined, zooIso5)
  }
  return(IsoCombined)
}
```

```{r}
wat <- IsoCompare(gnip_puertomontt.csv, gnip_goughisland.csv, gnip_marionisland.csv, gnip_capegrim.csv, gnip_margate.csv)
colnames(wat) <- c("PuertoMontt","Gough","Marion","CapeGrim","Margate")
head(wat)
```

```{r}
plot(wat, plot.type = 'multiple', col = c('red', 'blue', 'green', 'yellow', 'black'), lwd=2)
```



```{r}
stl(iso2, s.window='periodic')
```

Utilizing noaaGet for multiple sites

```{r}
sites <- c('GHCND:CI000085799','GHCND:SHM00068906','GHCND:SF000068994','GHCND:ASN00091245','GHCND:ASN00094125')
names(sites) <- c('PuertoMontt','Gough','Marion','CapeGrim','Margate')
sites
```

```{r}
for (x in 1:5){
  for (y in c('PRCP','TAVG')){
    DataTemp <- noaaGet(sites[[x]], y, 1980, 2018)
    assign(paste0(names(sites[x]),y), DataTemp)
  }
}
```



Everything below is deseasonalizing. Hard stuff



```{r}
testdata <- grim_data$value
testdata
```


```{r}
helpme <- ts(testdata)
stl(helpme,"periodic")
```
